
const table2024 = [
    {
        name: 'Athletico',
        acronym: 'CAP',
        points: 0,
        victories: 0,
        draws: 0,
        defeats: 0,
        goalsScored: 0,
        goalsConceded: 0,
        goalsBalance: 0,
    },
    {
      name: 'Atlético-GO',
      acronym: 'ACG',
      points: 0,
      victories: 0,
      draws: 0,
      defeats: 0,
      goalsScored: 0,
      goalsConceded: 0,
      goalsBalance: 0,
    },
    {
      name: 'Atlético-MG',
      acronym: 'CAM',
      points: 0,
      victories: 0,
      draws: 0,
      defeats: 0,
      goalsScored: 0,
      goalsConceded: 0,
      goalsBalance: 0,
    },
    {
      name: 'Bahia',
      acronym: 'BAH',
      points: 0,
      victories: 0,
      draws: 0,
      defeats: 0,
      goalsScored: 0,
      goalsConceded: 0,
      goalsBalance: 0,
    },
    {
      name: 'Botafogo',
      acronym: 'BOT',
      points: 0,
      victories: 0,
      draws: 0,
      defeats: 0,
      goalsScored: 0,
      goalsConceded: 0,
      goalsBalance: 0,
    },
    {
      name: 'Bragantino',
      acronym: 'RBB',
      points: 0,
      victories: 0,
      draws: 0,
      defeats: 0,
      goalsScored: 0,
      goalsConceded: 0,
      goalsBalance: 0,
    },
    {
      name: 'Corinthians',
      acronym: 'COR',
      points: 0,
      victories: 0,
      draws: 0,
      defeats: 0,
      goalsScored: 0,
      goalsConceded: 0,
      goalsBalance: 0,
    },
    {
      name: 'Criciúma',
      acronym: 'CRI',
      points: 0,
      victories: 0,
      draws: 0,
      defeats: 0,
      goalsScored: 0,
      goalsConceded: 0,
      goalsBalance: 0,
    },
    {
      name: 'Cruzeiro',
      acronym: 'CRU',
      points: 0,
      victories: 0,
      draws: 0,
      defeats: 0,
      goalsScored: 0,
      goalsConceded: 0,
      goalsBalance: 0,
    },
    {
      name: 'Cuiabá',
      acronym: 'CUI',
      points: 0,
      victories: 0,
      draws: 0,
      defeats: 0,
      goalsScored: 0,
      goalsConceded: 0,
      goalsBalance: 0,
    },
    {
      name: 'Flamengo',
      acronym: 'FLA',
      points: 0,
      victories: 0,
      draws: 0,
      defeats: 0,
      goalsScored: 0,
      goalsConceded: 0,
      goalsBalance: 0,
    },
    {
      name: 'Fluminense',
      acronym: 'FLU',
      points: 0,
      victories: 0,
      draws: 0,
      defeats: 0,
      goalsScored: 0,
      goalsConceded: 0,
      goalsBalance: 0,
    },
    {
      name: 'Fortaleza',
      acronym: 'FOR',
      points: 0,
      victories: 0,
      draws: 0,
      defeats: 0,
      goalsScored: 0,
      goalsConceded: 0,
      goalsBalance: 0,
    },
    {
      name: 'Grêmio',
      acronym: 'GRE',
      points: 0,
      victories: 0,
      draws: 0,
      defeats: 0,
      goalsScored: 0,
      goalsConceded: 0,
      goalsBalance: 0,
    },
    {
      name: 'Internacional',
      acronym: 'INT',
      points: 0,
      victories: 0,
      draws: 0,
      defeats: 0,
      goalsScored: 0,
      goalsConceded: 0,
      goalsBalance: 0,
    },
    {
      name: 'Juventude',
      acronym: 'JUV',
      points: 0,
      victories: 0,
      draws: 0,
      defeats: 0,
      goalsScored: 0,
      goalsConceded: 0,
      goalsBalance: 0,
    },
    {
      name: 'Palmeiras',
      acronym: 'PAL',
      points: 0,
      victories: 0,
      draws: 0,
      defeats: 0,
      goalsScored: 0,
      goalsConceded: 0,
      goalsBalance: 0,
    },
    {
      name: 'São Paulo',
      acronym: 'SAO',
      points: 0,
      victories: 0,
      draws: 0,
      defeats: 0,
      goalsScored: 0,
      goalsConceded: 0,
      goalsBalance: 0,
    },
    {
      name: 'Vasco',
      acronym: 'VAS',
      points: 0,
      victories: 0,
      draws: 0,
      defeats: 0,
      goalsScored: 0,
      goalsConceded: 0,
      goalsBalance: 0,
    },
    {
      name: 'Vitória',
      acronym: 'VIT',
      points: 0,
      victories: 0,
      draws: 0,
      defeats: 0,
      goalsScored: 0,
      goalsConceded: 0,
      goalsBalance: 0,
    },
  ];
  
export default table2024;